site_name: Convert API
plugins:
  - search
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences 
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - tables
  - toc:
      title: On this page
      permalink: true
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  - md_in_html
  - meta
  - footnotes
  - def_list
  - attr_list
  - admonition
  - abbr
nav:
  - Home: index.md
  - Weather Embed:
    - Home: WeatherEmbed/index.md
    - API-Documentation: WeatherEmbed/API-Documentation.md
  - Product 2:
    - Home: Product2/index.md
    - API-Documentation: Product2/API-Documentation.md
theme:
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
  favicon: images/favicon.png
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  palette:
    scheme: default
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/goelajit
      name: ajitgoel on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ajitgoel
      name: ajitgoel on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ajitgoel/
      name: ajitgoel on Linkedin
  homepage: https://www.ajitgoel.com
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  version:
    provider: mike
copyright: Copyright &copy; 2022 - 2099 Ajit Goel